DEFAULT: &DEFAULT
  gpu_deny_list: [1, 2, 3]
  num_gpus_total: 4
  num_gpus_to_use: 1
  dropout: 0.6
  l2_lambda: 0.0
  is_super_gat: False
  is_link_gnn: False
  lr: 0.001
  epochs: 300
  seed: 42
  verbose: 2
  save_model: True
  save_ckpt_interval: 50
  save_last_only: False
  save_plot: False
  continue_training: False
  val_interval: 1
  num_total_runs: 1

GCN: &GCN
  model_name: GCN
  <<: *DEFAULT
  num_hidden_features: 128

GIN: &GIN
  model_name: GIN
  <<: *DEFAULT
  num_hidden_features: 128

GAT: &GAT
  model_name: GAT
  <<: *DEFAULT
  num_hidden_features: 8
  heads: 8
